[package]
name    = "aptos-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
aptos-light-client-types      = { workspace = true, features = ["ethabi", "serde", "bincode"] }
aptos-verifier                = { workspace = true }
bcs                           = { workspace = true }
cosmwasm-std                  = { workspace = true, features = ["abort"] }
hex-literal                   = { workspace = true }
ibc-union-light-client        = { workspace = true }
ibc-union-msg                 = { workspace = true }
rlp                           = { workspace = true }
serde                         = { workspace = true, features = ["derive"] }
serde-utils                   = { workspace = true }
thiserror                     = { workspace = true }
unionlabs                     = { workspace = true }
unionlabs-cosmwasm-upgradable = { workspace = true }

[dev-dependencies]
aptos-crypto = { workspace = true }
aptos-types  = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []
