[package]
name    = "voyager-finality-module-bob"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
alloy          = { workspace = true, features = ["rpc", "rpc-types", "transports", "transport-http", "transport-ws", "reqwest", "reqwest-rustls-tls", "provider-ws"] }
bob-client     = { workspace = true }
embed-commit   = { workspace = true }
ibc-union-spec = { workspace = true, features = ["serde", "ethabi"] }
jsonrpsee      = { workspace = true, features = ["macros", "server", "tracing"] }
serde          = { workspace = true, features = ["derive"] }
tokio          = { workspace = true }
tracing        = { workspace = true }
unionlabs      = { workspace = true }
voyager-sdk    = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
