[fmt]
bracket_spacing              = false
contract_new_lines           = false
hex_underscore               = "remove"
ignore                       = []
int_types                    = "long"
line_length                  = 80
multiline_func_header        = "params_first"
number_underscore            = "preserve"
override_spacing             = false
quote_style                  = "double"
single_line_statement_blocks = "preserve"
sort_imports                 = false
tab_width                    = 4
wrap_comments                = false

[profile.default]
ast            = true
bytecode_hash  = "none"
cbor_metadata  = false
fs_permissions = [{ access = "read", path = "./" }, { access = "write", path = "contracts.json" }]
gas_reports    = ["*"]
optimizer      = true
optimizer_runs = 10_000
solc_version   = "0.8.27"
sparse_mode    = false
src            = "evm/scripts"
test           = "evm/tests/src"
via_ir         = true
