
[workspace]
members = [
  "cairo/ibc",
  "cairo/zkgm"
]

[workspace.dependencies]
alexandria_bytes = { git = "https://github.com/aeryz/alexandria", rev = "17fe9370daa56a8ef26f69a6b0fc7a309c015b18" }
alexandria_encoding = { git = "https://github.com/aeryz/alexandria", rev = "17fe9370daa56a8ef26f69a6b0fc7a309c015b18" }
alexandria_evm = { git = "https://github.com/aeryz/alexandria", rev = "17fe9370daa56a8ef26f69a6b0fc7a309c015b18" }
starknet = "2.12.2"
ibc = { path = "cairo/ibc" }
