
[workspace]
members = [
  "cairo/ibc",
  "cairo/zkgm"
]

[workspace.dependencies]
alexandria_bytes = { git = "https://github.com/aeryz/alexandria", rev = "def7a1a06a9bf01922167a449dafed714a1be2c5" }
alexandria_encoding = { git = "https://github.com/aeryz/alexandria", rev = "def7a1a06a9bf01922167a449dafed714a1be2c5" }
alexandria_evm = { git = "https://github.com/aeryz/alexandria", rev = "def7a1a06a9bf01922167a449dafed714a1be2c5" }
starknet = "2.12.2"
ibc = { path = "cairo/ibc" }
