[package]
name = "vault"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
ibc = { local = "../ibc" }
# zkgm = { local = "../ucs03_zkgm" }

[addresses]
vault = "_"
ibc = "_"
zkgm = "_"

[dev-dependencies]
[dev-addresses]
vault = "0x111"
ibc = "0x222"
zkgm = "0x333"
