[package]
name    = "access-managed-example"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
access-managed       = { workspace = true, features = ["library"] }
access-manager-types = { workspace = true }
cosmwasm-std         = { workspace = true }
depolama             = { workspace = true }
embed-commit         = { workspace = true }
frissitheto          = { workspace = true }
serde                = { workspace = true, features = ["derive"] }
thiserror            = { workspace = true }
unionlabs-encoding   = { workspace = true, features = ["bincode"] }
