[package]
name    = "voyager-state-module-solana"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
embed-commit             = { workspace = true }
ibc-union-spec           = { workspace = true, features = ["serde", "ethabi"] }
jsonrpsee                = { workspace = true, features = ["macros", "server", "tracing"] }
moka                     = { workspace = true, features = ["future"] }
serde                    = { workspace = true, features = ["derive"] }
serde_json               = { workspace = true }
solana-address           = { workspace = true }
solana-client            = { workspace = true }
solana-commitment-config = { workspace = true }
solana-sdk               = { workspace = true }
tokio                    = { workspace = true }
tracing                  = { workspace = true }
unionlabs                = { workspace = true, features = ["ethabi"] }
voyager-sdk              = { workspace = true }
