[package]
name    = "voyager-client-module-trusted-mpt"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
embed-commit                   = { workspace = true }
ethereum-light-client-types    = { workspace = true, features = ["serde", "bincode", "ethabi"] }
jsonrpsee                      = { workspace = true, features = ["macros", "server", "tracing"] }
serde                          = { workspace = true, features = ["derive"] }
serde_json                     = { workspace = true }
tokio                          = { workspace = true }
tracing                        = { workspace = true }
trusted-mpt-light-client-types = { workspace = true, features = ["serde", "ethabi", "bincode"] }
unionlabs                      = { workspace = true, features = ["bincode"] }
voyager-message                = { workspace = true }
voyager-vm                     = { workspace = true }
