//lint:file-ignore SA1019 This code is generated
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: differedack/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	types1 "github.com/cosmos/ibc-go/v8/modules/apps/transfer/types"
	types "github.com/cosmos/ibc-go/v8/modules/core/04-channel/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgWriteDifferedAck struct {
	Sender             string                          `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty" yaml:"sender"`
	Packet             *types.Packet                   `protobuf:"bytes,2,opt,name=packet,proto3" json:"packet,omitempty"`
	Data               *types1.FungibleTokenPacketData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	DifferedPacketInfo *DifferedPacketInfo             `protobuf:"bytes,4,opt,name=differedPacketInfo,proto3" json:"differedPacketInfo,omitempty"`
	Ack                *types.Acknowledgement          `protobuf:"bytes,5,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (m *MsgWriteDifferedAck) Reset()         { *m = MsgWriteDifferedAck{} }
func (m *MsgWriteDifferedAck) String() string { return proto.CompactTextString(m) }
func (*MsgWriteDifferedAck) ProtoMessage()    {}
func (*MsgWriteDifferedAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b4f63b11e8449f5, []int{0}
}
func (m *MsgWriteDifferedAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWriteDifferedAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWriteDifferedAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWriteDifferedAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWriteDifferedAck.Merge(m, src)
}
func (m *MsgWriteDifferedAck) XXX_Size() int {
	return m.Size()
}
func (m *MsgWriteDifferedAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWriteDifferedAck.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWriteDifferedAck proto.InternalMessageInfo

func (m *MsgWriteDifferedAck) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgWriteDifferedAck) GetPacket() *types.Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (m *MsgWriteDifferedAck) GetData() *types1.FungibleTokenPacketData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MsgWriteDifferedAck) GetDifferedPacketInfo() *DifferedPacketInfo {
	if m != nil {
		return m.DifferedPacketInfo
	}
	return nil
}

func (m *MsgWriteDifferedAck) GetAck() *types.Acknowledgement {
	if m != nil {
		return m.Ack
	}
	return nil
}

type MsgWriteDifferedAckResponse struct {
}

func (m *MsgWriteDifferedAckResponse) Reset()         { *m = MsgWriteDifferedAckResponse{} }
func (m *MsgWriteDifferedAckResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWriteDifferedAckResponse) ProtoMessage()    {}
func (*MsgWriteDifferedAckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b4f63b11e8449f5, []int{1}
}
func (m *MsgWriteDifferedAckResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWriteDifferedAckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWriteDifferedAckResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWriteDifferedAckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWriteDifferedAckResponse.Merge(m, src)
}
func (m *MsgWriteDifferedAckResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWriteDifferedAckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWriteDifferedAckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWriteDifferedAckResponse proto.InternalMessageInfo

type DifferedPacketInfo struct {
	OriginalSenderAddress  string `protobuf:"bytes,1,opt,name=original_sender_address,json=originalSenderAddress,proto3" json:"original_sender_address,omitempty"`
	RefundChannelId        string `protobuf:"bytes,2,opt,name=refund_channel_id,json=refundChannelId,proto3" json:"refund_channel_id,omitempty"`
	RefundPortId           string `protobuf:"bytes,3,opt,name=refund_port_id,json=refundPortId,proto3" json:"refund_port_id,omitempty"`
	PacketSrcChannelId     string `protobuf:"bytes,4,opt,name=packet_src_channel_id,json=packetSrcChannelId,proto3" json:"packet_src_channel_id,omitempty"`
	PacketSrcPortId        string `protobuf:"bytes,5,opt,name=packet_src_port_id,json=packetSrcPortId,proto3" json:"packet_src_port_id,omitempty"`
	PacketTimeoutTimestamp uint64 `protobuf:"varint,6,opt,name=packet_timeout_timestamp,json=packetTimeoutTimestamp,proto3" json:"packet_timeout_timestamp,omitempty"`
	PacketTimeoutHeight    string `protobuf:"bytes,7,opt,name=packet_timeout_height,json=packetTimeoutHeight,proto3" json:"packet_timeout_height,omitempty"`
	PacketData             []byte `protobuf:"bytes,8,opt,name=packet_data,json=packetData,proto3" json:"packet_data,omitempty"`
	RefundSequence         uint64 `protobuf:"varint,9,opt,name=refund_sequence,json=refundSequence,proto3" json:"refund_sequence,omitempty"`
	Timeout                uint64 `protobuf:"varint,10,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Nonrefundable          bool   `protobuf:"varint,11,opt,name=nonrefundable,proto3" json:"nonrefundable,omitempty"`
}

func (m *DifferedPacketInfo) Reset()         { *m = DifferedPacketInfo{} }
func (m *DifferedPacketInfo) String() string { return proto.CompactTextString(m) }
func (*DifferedPacketInfo) ProtoMessage()    {}
func (*DifferedPacketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b4f63b11e8449f5, []int{2}
}
func (m *DifferedPacketInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DifferedPacketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DifferedPacketInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DifferedPacketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DifferedPacketInfo.Merge(m, src)
}
func (m *DifferedPacketInfo) XXX_Size() int {
	return m.Size()
}
func (m *DifferedPacketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DifferedPacketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DifferedPacketInfo proto.InternalMessageInfo

func (m *DifferedPacketInfo) GetOriginalSenderAddress() string {
	if m != nil {
		return m.OriginalSenderAddress
	}
	return ""
}

func (m *DifferedPacketInfo) GetRefundChannelId() string {
	if m != nil {
		return m.RefundChannelId
	}
	return ""
}

func (m *DifferedPacketInfo) GetRefundPortId() string {
	if m != nil {
		return m.RefundPortId
	}
	return ""
}

func (m *DifferedPacketInfo) GetPacketSrcChannelId() string {
	if m != nil {
		return m.PacketSrcChannelId
	}
	return ""
}

func (m *DifferedPacketInfo) GetPacketSrcPortId() string {
	if m != nil {
		return m.PacketSrcPortId
	}
	return ""
}

func (m *DifferedPacketInfo) GetPacketTimeoutTimestamp() uint64 {
	if m != nil {
		return m.PacketTimeoutTimestamp
	}
	return 0
}

func (m *DifferedPacketInfo) GetPacketTimeoutHeight() string {
	if m != nil {
		return m.PacketTimeoutHeight
	}
	return ""
}

func (m *DifferedPacketInfo) GetPacketData() []byte {
	if m != nil {
		return m.PacketData
	}
	return nil
}

func (m *DifferedPacketInfo) GetRefundSequence() uint64 {
	if m != nil {
		return m.RefundSequence
	}
	return 0
}

func (m *DifferedPacketInfo) GetTimeout() uint64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *DifferedPacketInfo) GetNonrefundable() bool {
	if m != nil {
		return m.Nonrefundable
	}
	return false
}

func init() {
	proto.RegisterType((*MsgWriteDifferedAck)(nil), "differedack.v1beta1.MsgWriteDifferedAck")
	proto.RegisterType((*MsgWriteDifferedAckResponse)(nil), "differedack.v1beta1.MsgWriteDifferedAckResponse")
	proto.RegisterType((*DifferedPacketInfo)(nil), "differedack.v1beta1.DifferedPacketInfo")
}

func init() { proto.RegisterFile("differedack/v1beta1/tx.proto", fileDescriptor_4b4f63b11e8449f5) }

var fileDescriptor_4b4f63b11e8449f5 = []byte{
	// 664 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x41, 0x4f, 0xdb, 0x3c,
	0x18, 0xc7, 0x09, 0x2d, 0x05, 0x5c, 0x78, 0xdf, 0x17, 0xf3, 0x32, 0xb2, 0xb2, 0x95, 0xae, 0x42,
	0xa2, 0x30, 0x29, 0x59, 0x8b, 0x36, 0x4d, 0xdc, 0x60, 0xd5, 0xb4, 0x1e, 0x90, 0x50, 0x40, 0x42,
	0xda, 0xa5, 0x72, 0x1d, 0x37, 0x58, 0x4d, 0xed, 0xcc, 0x76, 0x3b, 0x90, 0x76, 0x98, 0xf6, 0x09,
	0xf6, 0x51, 0xf8, 0x18, 0x3b, 0x72, 0xdc, 0x09, 0x4d, 0x70, 0xe0, 0xbe, 0xc3, 0xce, 0x53, 0x6c,
	0x87, 0x15, 0x91, 0xc3, 0x4e, 0x09, 0xcf, 0xff, 0xf7, 0xfc, 0xfd, 0xe7, 0xf1, 0xd3, 0x80, 0x27,
	0x21, 0xed, 0xf7, 0x89, 0x20, 0x21, 0xc2, 0x03, 0x7f, 0xdc, 0xec, 0x11, 0x85, 0x9a, 0xbe, 0x3a,
	0xf3, 0x12, 0xc1, 0x15, 0x87, 0xcb, 0x13, 0xaa, 0x67, 0xd5, 0xca, 0xff, 0x11, 0x8f, 0xb8, 0xd6,
	0xfd, 0xf4, 0xcd, 0xa0, 0x95, 0x55, 0xcc, 0xe5, 0x90, 0x4b, 0x7f, 0x28, 0x23, 0x7f, 0xdc, 0x4c,
	0x1f, 0x56, 0x78, 0x46, 0x7b, 0xd8, 0xc7, 0x5c, 0x10, 0x1f, 0x9f, 0x22, 0xc6, 0x48, 0x9c, 0xca,
	0xf6, 0xd5, 0x22, 0x5b, 0x29, 0x82, 0x92, 0x24, 0xa6, 0x18, 0x29, 0xca, 0x99, 0xf4, 0x95, 0x40,
	0x4c, 0xf6, 0x89, 0xf0, 0xc7, 0x2d, 0x3f, 0x41, 0x78, 0x40, 0x94, 0x41, 0xeb, 0x57, 0xd3, 0x60,
	0xf9, 0x40, 0x46, 0x27, 0x82, 0x2a, 0xd2, 0xb6, 0xe1, 0xf6, 0xf0, 0x00, 0x6e, 0x81, 0x92, 0x24,
	0x2c, 0x24, 0xc2, 0x75, 0x6a, 0x4e, 0x63, 0x7e, 0x7f, 0xe9, 0xe7, 0xd5, 0xfa, 0xe2, 0x39, 0x1a,
	0xc6, 0xbb, 0x75, 0x53, 0xaf, 0x07, 0x16, 0x80, 0x3b, 0xa0, 0x64, 0x2c, 0xdd, 0xe9, 0x9a, 0xd3,
	0x28, 0xb7, 0xd6, 0x3c, 0xda, 0xc3, 0x5e, 0x9a, 0xd0, 0xcb, 0x62, 0x8d, 0x9b, 0xde, 0xa1, 0x46,
	0x02, 0x8b, 0xc2, 0x0e, 0x28, 0x86, 0x48, 0x21, 0xb7, 0xa0, 0x5b, 0x5e, 0xea, 0x96, 0xc9, 0xc4,
	0x5e, 0x96, 0xd8, 0x1b, 0xb7, 0xbc, 0xb7, 0x23, 0x16, 0xd1, 0x5e, 0x4c, 0x8e, 0xf9, 0x80, 0x30,
	0x63, 0xd4, 0x46, 0x0a, 0x05, 0xda, 0x02, 0x9e, 0x00, 0x98, 0x8d, 0xd5, 0x68, 0x1d, 0xd6, 0xe7,
	0x6e, 0x51, 0x1b, 0x6f, 0x7a, 0x39, 0x13, 0xf7, 0xda, 0x0f, 0xf0, 0x20, 0xc7, 0x02, 0xbe, 0x02,
	0x05, 0x84, 0x07, 0xee, 0x8c, 0x76, 0xda, 0xc8, 0xfd, 0xaf, 0xf6, 0xf0, 0x80, 0xf1, 0x8f, 0x31,
	0x09, 0x23, 0x32, 0x24, 0x4c, 0x05, 0x69, 0xc3, 0x6e, 0xf9, 0xcb, 0xed, 0xc5, 0xb6, 0x9d, 0x4e,
	0xfd, 0x29, 0x58, 0xcb, 0x99, 0x6f, 0x40, 0x64, 0xc2, 0x99, 0x24, 0xf5, 0x5f, 0x05, 0x00, 0xdb,
	0x79, 0x47, 0xaf, 0x72, 0x41, 0x23, 0xca, 0x50, 0xdc, 0x35, 0x46, 0x5d, 0x14, 0x86, 0x82, 0x48,
	0x69, 0xee, 0x23, 0x58, 0xc9, 0xe4, 0x23, 0xad, 0xee, 0x19, 0x11, 0x6e, 0x83, 0x25, 0x41, 0xfa,
	0x23, 0x16, 0x76, 0x6d, 0xc8, 0x2e, 0x0d, 0xf5, 0xb5, 0xcc, 0x07, 0xff, 0x1a, 0xe1, 0x8d, 0xa9,
	0x77, 0x42, 0xb8, 0x01, 0xfe, 0xb1, 0x6c, 0xc2, 0x85, 0x4a, 0xc1, 0x82, 0x06, 0x17, 0x4c, 0xf5,
	0x90, 0x0b, 0xd5, 0x09, 0x61, 0x13, 0xac, 0x98, 0x2b, 0xeb, 0x4a, 0x81, 0x27, 0x5d, 0x8b, 0x1a,
	0x86, 0x46, 0x3c, 0x12, 0xf8, 0x8f, 0xf1, 0x73, 0x00, 0x27, 0x5a, 0x32, 0xf3, 0x19, 0x93, 0xe2,
	0x8e, 0xb7, 0xfe, 0xaf, 0x81, 0x6b, 0x61, 0x45, 0x87, 0x84, 0x8f, 0xcc, 0x53, 0x2a, 0x34, 0x4c,
	0xdc, 0x52, 0xcd, 0x69, 0x14, 0x83, 0x47, 0x46, 0x3f, 0x36, 0xf2, 0x71, 0xa6, 0xc2, 0xd6, 0x5d,
	0xb2, 0xac, 0xf3, 0x94, 0xd0, 0xe8, 0x54, 0xb9, 0xb3, 0xfa, 0xa4, 0xe5, 0x7b, 0x6d, 0xef, 0xb4,
	0x04, 0xd7, 0x41, 0xd9, 0xf6, 0xe8, 0xed, 0x9b, 0xab, 0x39, 0x8d, 0x85, 0x00, 0x24, 0x77, 0x2b,
	0x05, 0x37, 0x81, 0x9d, 0x53, 0x57, 0x92, 0x0f, 0x23, 0xc2, 0x30, 0x71, 0xe7, 0x75, 0x0a, 0x3b,
	0xab, 0x23, 0x5b, 0x85, 0x2e, 0x98, 0xb5, 0xc7, 0xba, 0x40, 0x03, 0xd9, 0x9f, 0x70, 0x03, 0x2c,
	0x32, 0xce, 0x0c, 0x8e, 0x7a, 0x31, 0x71, 0xcb, 0x35, 0xa7, 0x31, 0x17, 0xdc, 0x2f, 0xb6, 0x3e,
	0x81, 0xc2, 0x81, 0x8c, 0x20, 0x03, 0xff, 0x3d, 0xf8, 0xed, 0x35, 0x72, 0x97, 0x36, 0x67, 0x8b,
	0x2a, 0x2f, 0xfe, 0x96, 0xcc, 0xf6, 0xad, 0x32, 0xf3, 0xf9, 0xf6, 0x62, 0xdb, 0xd9, 0xdf, 0xf9,
	0x76, 0x5d, 0x75, 0x2e, 0xaf, 0xab, 0xce, 0x8f, 0xeb, 0xaa, 0xf3, 0xf5, 0xa6, 0x3a, 0x75, 0x79,
	0x53, 0x9d, 0xfa, 0x7e, 0x53, 0x9d, 0x7a, 0xff, 0x78, 0xc4, 0x28, 0x67, 0xfe, 0x99, 0x3f, 0xf9,
	0x21, 0x53, 0xe7, 0x09, 0x91, 0xbd, 0x92, 0xfe, 0x64, 0xec, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0x73, 0x76, 0xc0, 0x9c, 0xe4, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	WriteDifferedAck(ctx context.Context, in *MsgWriteDifferedAck, opts ...grpc.CallOption) (*MsgWriteDifferedAckResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) WriteDifferedAck(ctx context.Context, in *MsgWriteDifferedAck, opts ...grpc.CallOption) (*MsgWriteDifferedAckResponse, error) {
	out := new(MsgWriteDifferedAckResponse)
	err := c.cc.Invoke(ctx, "/differedack.v1beta1.Msg/WriteDifferedAck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	WriteDifferedAck(context.Context, *MsgWriteDifferedAck) (*MsgWriteDifferedAckResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) WriteDifferedAck(ctx context.Context, req *MsgWriteDifferedAck) (*MsgWriteDifferedAckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteDifferedAck not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_WriteDifferedAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWriteDifferedAck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WriteDifferedAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/differedack.v1beta1.Msg/WriteDifferedAck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WriteDifferedAck(ctx, req.(*MsgWriteDifferedAck))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "differedack.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteDifferedAck",
			Handler:    _Msg_WriteDifferedAck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "differedack/v1beta1/tx.proto",
}

func (m *MsgWriteDifferedAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWriteDifferedAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWriteDifferedAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Ack != nil {
		{
			size, err := m.Ack.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.DifferedPacketInfo != nil {
		{
			size, err := m.DifferedPacketInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Data != nil {
		{
			size, err := m.Data.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Packet != nil {
		{
			size, err := m.Packet.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWriteDifferedAckResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWriteDifferedAckResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWriteDifferedAckResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *DifferedPacketInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DifferedPacketInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DifferedPacketInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Nonrefundable {
		i--
		if m.Nonrefundable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.Timeout != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Timeout))
		i--
		dAtA[i] = 0x50
	}
	if m.RefundSequence != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RefundSequence))
		i--
		dAtA[i] = 0x48
	}
	if len(m.PacketData) > 0 {
		i -= len(m.PacketData)
		copy(dAtA[i:], m.PacketData)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PacketData)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.PacketTimeoutHeight) > 0 {
		i -= len(m.PacketTimeoutHeight)
		copy(dAtA[i:], m.PacketTimeoutHeight)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PacketTimeoutHeight)))
		i--
		dAtA[i] = 0x3a
	}
	if m.PacketTimeoutTimestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PacketTimeoutTimestamp))
		i--
		dAtA[i] = 0x30
	}
	if len(m.PacketSrcPortId) > 0 {
		i -= len(m.PacketSrcPortId)
		copy(dAtA[i:], m.PacketSrcPortId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PacketSrcPortId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.PacketSrcChannelId) > 0 {
		i -= len(m.PacketSrcChannelId)
		copy(dAtA[i:], m.PacketSrcChannelId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PacketSrcChannelId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RefundPortId) > 0 {
		i -= len(m.RefundPortId)
		copy(dAtA[i:], m.RefundPortId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RefundPortId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RefundChannelId) > 0 {
		i -= len(m.RefundChannelId)
		copy(dAtA[i:], m.RefundChannelId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RefundChannelId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OriginalSenderAddress) > 0 {
		i -= len(m.OriginalSenderAddress)
		copy(dAtA[i:], m.OriginalSenderAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OriginalSenderAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgWriteDifferedAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Packet != nil {
		l = m.Packet.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Data != nil {
		l = m.Data.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DifferedPacketInfo != nil {
		l = m.DifferedPacketInfo.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Ack != nil {
		l = m.Ack.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWriteDifferedAckResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *DifferedPacketInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OriginalSenderAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RefundChannelId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RefundPortId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PacketSrcChannelId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PacketSrcPortId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PacketTimeoutTimestamp != 0 {
		n += 1 + sovTx(uint64(m.PacketTimeoutTimestamp))
	}
	l = len(m.PacketTimeoutHeight)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PacketData)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.RefundSequence != 0 {
		n += 1 + sovTx(uint64(m.RefundSequence))
	}
	if m.Timeout != 0 {
		n += 1 + sovTx(uint64(m.Timeout))
	}
	if m.Nonrefundable {
		n += 2
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgWriteDifferedAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWriteDifferedAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWriteDifferedAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Packet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Packet == nil {
				m.Packet = &types.Packet{}
			}
			if err := m.Packet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Data == nil {
				m.Data = &types1.FungibleTokenPacketData{}
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DifferedPacketInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DifferedPacketInfo == nil {
				m.DifferedPacketInfo = &DifferedPacketInfo{}
			}
			if err := m.DifferedPacketInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ack", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ack == nil {
				m.Ack = &types.Acknowledgement{}
			}
			if err := m.Ack.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWriteDifferedAckResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWriteDifferedAckResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWriteDifferedAckResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DifferedPacketInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DifferedPacketInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DifferedPacketInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginalSenderAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginalSenderAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefundChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefundChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefundPortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefundPortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PacketSrcChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PacketSrcChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PacketSrcPortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PacketSrcPortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PacketTimeoutTimestamp", wireType)
			}
			m.PacketTimeoutTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PacketTimeoutTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PacketTimeoutHeight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PacketTimeoutHeight = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PacketData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PacketData = append(m.PacketData[:0], dAtA[iNdEx:postIndex]...)
			if m.PacketData == nil {
				m.PacketData = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefundSequence", wireType)
			}
			m.RefundSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RefundSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timeout", wireType)
			}
			m.Timeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timeout |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonrefundable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Nonrefundable = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
