[package]
name    = "build-evm-deployer-tx"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
alloy        = { workspace = true, features = ["consensus", "eips"] }
clap         = { workspace = true, features = ["derive", "env", "error-context", "help"] }
embed-commit = { workspace = true }
