[package]
authors = ["Union Labs"]
edition = "2021"
license = "BSL-1.1"
name    = "cometbls-light-client"
publish = false
version = "0.1.0"

[lints]
workspace = true

[package.metadata.crane]
test-include = ["cosmwasm/ibc-union/light-clients/cometbls/src/test"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cometbls-groth16-verifier   = { workspace = true }
cometbls-light-client-types = { workspace = true, features = ["serde", "ethabi", "bincode"] }
cosmwasm-std                = { workspace = true, features = ["abort", "iterator"] }
ibc-union-light-client      = { workspace = true }
ibc-union-msg               = { workspace = true }
ics23                       = { workspace = true }
serde                       = { workspace = true, features = ["derive"] }
thiserror                   = { workspace = true }
unionlabs                   = { workspace = true, features = ["ethabi"] }

[dev-dependencies]
base64      = { workspace = true }
hex-literal = { workspace = true }
lazy_static = "1.4.0"
serde_json  = { workspace = true }


[features]
library = []
