version: 3
endpoint: https://noble-pika-27.hasura.app
admin_secret: 3N5Mt2f4Y1AC7dE663AsGqRy66yiHBuZ3RMgUjM6X4Q3Ma8G2yKmVoasdasdsadasda
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
