[package]
name    = "berachain-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[package.metadata.crane]
test-include = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
beacon-api-types              = { workspace = true, features = ["ssz"] }
berachain-light-client-types  = { workspace = true, features = ["serde", "ethabi", "bincode"] }
cometbft-types                = { workspace = true, features = ["hash"] }
cosmwasm-std                  = { workspace = true, features = ["abort", "cosmwasm_2_1"] }
embed-commit                  = { workspace = true }
ethereum-light-client         = { workspace = true, features = ["library"] }
ethereum-light-client-types   = { workspace = true, features = ["serde", "ethabi"] }
evm-storage-verifier          = { workspace = true }
frissitheto                   = { workspace = true }
ibc-union-light-client        = { workspace = true }
ibc-union-msg                 = { workspace = true }
ics23                         = { workspace = true }
protos                        = { workspace = true }
serde                         = { workspace = true, features = ["derive"] }
tendermint-light-client-types = { workspace = true, features = ["serde", "bincode"] }
tendermint-verifier           = { workspace = true }
thiserror                     = { workspace = true }
unionlabs                     = { workspace = true, features = ["ssz"] }

[dev-dependencies]
base64                = { workspace = true }
ethereum-light-client = { workspace = true }
lazy_static           = "1.5.0"
serde_json            = { workspace = true }

[features]
