[package]
name    = "multicall"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
cosmwasm-std         = { workspace = true, features = ["std", "stargate"] }
embed-commit         = { workspace = true }
serde                = { workspace = true, features = ["derive"] }
thiserror            = { workspace = true }
unionlabs-primitives = { workspace = true, features = ["serde"] }

[dev-dependencies]
hex        = { workspace = true }
serde_json = { workspace = true }
