[package]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "slot-calculator"
publish      = false
repository   = { workspace = true }
version      = "0.1.0"

[lints]
workspace = true

[dependencies]
clap         = { workspace = true, features = ["derive", "help"] }
hex-literal  = { workspace = true }
proc-macro2  = "1.0.93"
slotlib      = { workspace = true }
syn-solidity = "0.8.19"
typed-arena  = "2.0"
unionlabs    = { workspace = true, features = ["rlp"] }
