[package]
name    = "scroll-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std                = { workspace = true, features = ["abort"] }
embed-commit                = { workspace = true }
ethereum-light-client       = { workspace = true, features = ["library"] }
ethereum-light-client-types = { workspace = true }
ibc-union-light-client      = { workspace = true }
ibc-union-msg               = { workspace = true }
scroll-codec                = { workspace = true }
scroll-light-client-types   = { workspace = true, features = ["proto"] }
scroll-verifier             = { workspace = true }
thiserror                   = { workspace = true }
unionlabs                   = { workspace = true, features = ["ethabi"] }

[dev-dependencies]
base64     = { workspace = true }
hex        = { workspace = true }
serde_json = { workspace = true }

[features]
library = []
