{ ... }: {
  perSystem = { self', pkgs, proto, crane, system, config, ensureAtRepositoryRoot, ... }:
    {
      # Short for todo-comment
      packages.tdc = pkgs.writeShellApplication {
        name = "tdc";
        runtimeInputs = with pkgs; [ gh coreutils ];
        text = ''
          gh issue create -t "$1" -b "_Generated by Union's \'todo-comment\' app_" --label "todo comment" -a "@me" | tail -n 1 | sed 's|https://github.com/\(.*\)/issues/\(.*\)|\1#\2|'
        '';
      };
    };
}
  
  
