[package]
name    = "ucs03-zkgm-api"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
alloy-primitives  = { workspace = true }
alloy-sol-types   = { workspace = true }
cosmwasm-schema   = { workspace = true }
cosmwasm-std      = { workspace = true, features = ["std"] }
enumorph          = { workspace = true }
ibc-union-spec    = { workspace = true, features = ["schemars", "serde"] }
token-factory-api = { workspace = true }
unionlabs         = { workspace = true, default-features = false }
