[package]
name    = "voyager-state-module-cosmos-sdk"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
clap              = { workspace = true, features = ["derive"] }
cometbft-rpc      = { workspace = true }
cosmos-sdk-event  = { workspace = true }
embed-commit      = { workspace = true }
futures.workspace = true
ibc-classic-spec  = { workspace = true }
ibc-union-msg     = { workspace = true }
ibc-union-spec    = { workspace = true }
jsonrpsee         = { workspace = true, features = ["macros", "server", "tracing"] }
protos            = { workspace = true }
serde             = { workspace = true, features = ["derive"] }
serde-utils       = { workspace = true }
serde_json        = { workspace = true }
thiserror         = { workspace = true }
tokio             = { workspace = true }
tracing           = { workspace = true }
unionlabs         = { workspace = true }
voyager-sdk       = { workspace = true }
