[package]
name    = "voyager-proof-module-ethereum"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
alloy                       = { workspace = true, features = ["rpc", "rpc-types", "transports", "transport-http", "transport-ws", "reqwest", "provider-ws"] }
embed-commit                = { workspace = true }
ethereum-light-client-types = { workspace = true, features = ["serde"] }
ibc-union-spec              = { workspace = true, features = ["serde"] }
jsonrpsee                   = { workspace = true, features = ["macros", "server", "tracing"] }
serde                       = { workspace = true, features = ["derive"] }
serde_json                  = { workspace = true }
tokio                       = { workspace = true }
tracing                     = { workspace = true }
unionlabs                   = { workspace = true, features = ["ethabi"] }
voyager-message             = { workspace = true }
voyager-vm                  = { workspace = true }
