[package]
name    = "voyager-proof-module-ethermint"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
clap            = { workspace = true, features = ["derive"] }
cometbft-rpc    = { workspace = true }
embed-commit    = { workspace = true }
ibc-union-spec  = { workspace = true, features = ["serde"] }
jsonrpsee       = { workspace = true, features = ["macros", "server", "tracing"] }
prost           = { workspace = true }
protos          = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
thiserror       = { workspace = true }
tokio           = { workspace = true }
tracing         = { workspace = true }
unionlabs       = { workspace = true }
voyager-message = { workspace = true }
voyager-vm      = { workspace = true }
